"$CLOUD_REBUILD" FastNumber 32 dll release same
"$CLOUD_REBUILD" StockMysql 32 dll release only
"$CLOUD_REBUILD" StockCharge 32 dll release only
"$CLOUD_REBUILD" StockMarket 32 dll release only
"$CLOUD_REBUILD" StockIndicator 32 dll release only
"$CLOUD_REBUILD" StockFund 32 dll release only
"$CLOUD_REBUILD" StockType 32 dll release only
"$CLOUD_REBUILD" StockStrategy 32 dll release only
"$CLOUD_REBUILD" StockDraw 32 dll release only
"$CLOUD_REBUILD" StockSolution 32 dll release only
"$CLOUD_REBUILD" StockStorage 32 dll release only
"$CLOUD_REBUILD" StockTrade 32 dll release only
"$CLOUD_REBUILD" StockRetest 32 dll release only