call "%CLOUD_REBUILD%" FastNumber 32 dll debug same
call "%CLOUD_REBUILD%" StockMysql 32 dll debug only
call "%CLOUD_REBUILD%" StockCharge 32 dll debug only
call "%CLOUD_REBUILD%" StockMarket 32 dll debug only
call "%CLOUD_REBUILD%" StockIndicator 32 dll debug only
call "%CLOUD_REBUILD%" StockDraw 32 dll debug only
call "%CLOUD_REBUILD%" StockFund 32 dll debug only
call "%CLOUD_REBUILD%" StockStrategy 32 dll debug only
call "%CLOUD_REBUILD%" StockSolution 32 dll debug only
call "%CLOUD_REBUILD%" StockTrade 32 dll debug only
call "%CLOUD_REBUILD%" StockRetest 32 dll debug only