call "%CLOUD_REBUILD%" DialogManager 32 dll release same
call "%CLOUD_REBUILD%" StockDraw 32 dll release same
call "%CLOUD_REBUILD%" StockCharge 32 dll release only
call "%CLOUD_REBUILD%" StockFund 32 dll release only
call "%CLOUD_REBUILD%" CStopWatch 32 dll release only
call "%CLOUD_REBUILD%" ScreenScript 32 dll release same
call "%CLOUD_REBUILD%" CKeyboard 32 dll release only
call "%CLOUD_REBUILD%" CDump 32 dll release only
call "%CLOUD_REBUILD%" StockStrategy 32 dll release only
call "%CLOUD_REBUILD%" StockSolution 32 dll release only
call "%CLOUD_REBUILD%" StockTrade 32 dll release only
call "%CLOUD_REBUILD%" StockRetest 32 dll release only