"$CLOUD_REBUILD" DialogManager 32 dll debug same
"$CLOUD_REBUILD" StockMysql 32 dll debug same
"$CLOUD_REBUILD" Ctxt 32 dll debug same
"$CLOUD_REBUILD" StockMarket 32 dll debug only
"$CLOUD_REBUILD" CTaskThreadManager 32 dll debug same
"$CLOUD_REBUILD" StockIndicator 32 dll debug only
"$CLOUD_REBUILD" StockCharge 32 dll debug only
"$CLOUD_REBUILD" StockFund 32 dll debug only
"$CLOUD_REBUILD" CStopWatch 32 dll debug only
"$CLOUD_REBUILD" ScreenScript 32 dll debug same
"$CLOUD_REBUILD" CKeyboard 32 dll debug only
"$CLOUD_REBUILD" CDump 32 dll debug only
"$CLOUD_REBUILD" StockType 32 dll debug only
"$CLOUD_REBUILD" StockStrategy 32 dll debug only
"$CLOUD_REBUILD" StockDraw 32 dll debug only
"$CLOUD_REBUILD" StockSolution 32 dll debug only
"$CLOUD_REBUILD" StockStorage 32 dll debug only
"$CLOUD_REBUILD" StockTrade 32 dll debug only
"$CLOUD_REBUILD" StockRetest 32 dll debug only