#pragma once
#include "CorrespondParamMacro.h"

enum
{
	CLIENT_PID = 1,
	CONNECT_ID,
	CLIENT_NAME,
	SERVER_ID,
	SERVER_NAME,
	CLIENT_INIT_INFO,
	SERVER_INIT_INFO,
	CLIENT_INIT_RESPONSE_INFO,

	LOG_FUN_NAME = 10000,
	LOG_FILE_NAME,
	LOG_NAME,
	LOG_PROCESS_NAME,
	LOG_LEVEL,
	LOG_IS_SEND_SCREEN,
	LOG_IS_SEND_NET,
	LOG_IS_WRITE_LOG,
	LOG_BUFFER,
	LOG_THREAD_ID,
	LOG_INT_DATE_TIME,
	LOG_LOGIN_NAME,
	LOG_UNINIT,
	LOG_CLOSE,
	LOG_SET,
	LOG_SET_DEAL_LOG,

	DTWS_STOP = 20000,
	DTWS_FOLLOW,
	DTWS_HEAL,
	DTWS_RISE,
	DTWS_ATTACK,
	DTWS_JIDI,
	DTWS_CHANGSHOUGONG,
	DTWS_DACHE,
	DTWS_XIAOCHE,
	DTWS_BINGJIANCUN,
	DTWS_MUFENGLIN,
	DTWS_HUILUODAO,
	DTWS_LONGMENSHIKU,
	DTWS_DALEIGONG,
	DTWS_SUBMIT
};

enum StockEnum
{
	STOCK_RSI6 = 0,
	STOCK_RSI12,
	STOCK_RSI24,
	STOCK_WR10,
	STOCK_WR20
};

enum MessageType
{
	INIT,
	CLIENT_INIT,
	NET_CLIENT_CLIENT_INIT,
	NET_SERVER_CLIENT_INIT,
	CLIENT_INIT_RESPONSE,
	NET_SERVER_CLIENT_INIT_RESPONSE,
	SERVER_INIT,
	SERVER_INIT_RESPONSE,
	NET_SERVER_SERVER_INIT_RESPONSE,
	NET_CLIENT_CLIENT_INIT_RESPONSE,
	MESSAGE,
	NET_CLIENT_MESSAGE,
	NET_SERVER_MESSAGE,
	SERVER_MESSAGE,
	NET_SERVER_MESSAGE_RESPONSE,
	LOGTEST_MESSAGE,
	PROTO_MESSAGE,
	JSON_MESSAGE,
	XML_MESSAGE,
	HEART
};

enum
{
	PROJECT_LOGTEST = 1,
	PROJECT_DTWS
};

class CorrespondParamAPI CorrespondParam
{
public:
	CorrespondParam();
};