"$CLOUD_REBUILD" CStringManager 64 dll debug same
"$CLOUD_REBUILD" CSystem 64 dll debug same
"$CLOUD_REBUILD" ReadWriteMutex 64 dll debug same
"$CLOUD_REBUILD" IntDateTime 64 dll debug same
"$CLOUD_REBUILD" RapidJson 64 dll debug same
"$CLOUD_REBUILD" HttpService 64 dll debug same
"$CLOUD_REBUILD" LogManager 64 dll debug only
"$CLOUD_REBUILD" CDump 64 dll debug same
"$CLOUD_REBUILD" Cini 64 dll debug same
"$CLOUD_REBUILD" CTaskThreadManager 64 lib debug same
"$CLOUD_REBUILD" HiRedis 64 lib debug same
"$CLOUD_REBUILD" MysqlCpp 64 lib debug same
