"$CLOUD_REBUILD" CStringManager 64 lib release same
"$CLOUD_REBUILD" CSystem 64 lib release same
"$CLOUD_REBUILD" ReadWriteMutex 64 lib release same
"$CLOUD_REBUILD" IntDateTime 64 lib release same
"$CLOUD_REBUILD" RapidJson 64 lib release same
"$CLOUD_REBUILD" HttpService 64 lib release same
"$CLOUD_REBUILD" LogManager 64 lib release only
"$CLOUD_REBUILD" CDump 64 lib release same
"$CLOUD_REBUILD" Cini 64 lib release same
"$CLOUD_REBUILD" CTaskThreadManager 64 lib release same
"$CLOUD_REBUILD" HiRedis 64 lib release same
"$CLOUD_REBUILD" HiRedis 64 dll release only
"$CLOUD_REBUILD" MysqlCpp 64 lib release same
"$CLOUD_REBUILD" FFmpegCpp 64 lib release same