const API_HOST = '175.24.198.162'
const API_PORT = 5207
const API_PROTOCOL = 'http'

const LOCAL_API_HOST = '127.0.0.1'
const LOCAL_API_PORT = 5207

const USE_LOCAL_SERVER = false
const DEFAULT_REQUEST_TIMEOUT_MS = 30000
const DEFAULT_REQUEST_MAX_ATTEMPTS = 3
const API_REQUEST_MAX_CONCURRENCY = 4
const API_BACKGROUND_REQUEST_MAX_CONCURRENCY = 2
const API_REQUEST_PRIORITY_HIGH = 100
const API_REQUEST_PRIORITY_NORMAL = 50
const API_REQUEST_PRIORITY_LOW = 10

const VOICE_TTS_PROVIDER_NONE = 'none'
const VOICE_TTS_PROVIDER_WECHAT_PLUGIN = 'wechat_plugin'
const VOICE_TTS_PROVIDER_SERVER = 'server'
const VOICE_TTS_PROVIDER = VOICE_TTS_PROVIDER_SERVER
const VOICE_SERVER_TTS_PATH = '/api/voice/tts'
const VOICE_TTS_REQUEST_TIMEOUT_MS = 30000
const VOICE_TTS_MAX_ATTEMPTS = 3
const VOICE_TTS_RETRY_DELAY_MS = 300
const VOICE_PREPARE_REQUEST_TIMEOUT_MS = 30000
const VOICE_PREPARE_MAX_ATTEMPTS = 3
const VOICE_PREPARE_RETRY_DELAY_MS = 300
const VOICE_INITIAL_REQUIRED_AUDIO_WAIT_MS = 15000
const VOICE_REQUIRED_PREFETCH_TIMEOUT_MS = 95000
const VOICE_INITIAL_REQUIRED_FETCH_CONCURRENCY = 2
const VOICE_PREFETCH_QUEUE_CONCURRENCY = 2
const VOICE_BACKGROUND_PREFETCH_CONCURRENCY = 2
const VOICE_BACKGROUND_FETCH_WAIT_MS = 0
const VOICE_BACKGROUND_FETCH_TIMEOUT_MS = 15000
const VOICE_BACKGROUND_FETCH_MAX_ATTEMPTS = 2
const VOICE_FETCH_WAIT_MS = 30000
const VOICE_FETCH_MAX_ATTEMPTS = 3
const VOICE_PREFETCH_DOWNLOAD_AUDIO = false
const VOICE_AUDIO_DOWNLOAD_TIMEOUT_MS = 30000
const VOICE_REST_DURATION_GRACE_MS = 2500
const VOICE_REST_DURATION_REQUEST_TIMEOUT_MS = 30000
const VOICE_REST_DURATION_MAX_ATTEMPTS = 3
const VOICE_REST_DURATION_RETRY_DELAY_MS = 200
const VOICE_REST_FIXED_FETCH_TIMEOUT_MS = 2000
const VOICE_REST_FIXED_LOCAL_WAIT_MS = 1200
const VOICE_REST_DURATION_LOCAL_WAIT_MS = 1200
const VOICE_SEQUENCE_TIMEOUT_PADDING_MS = 4000
const VOICE_REST_SEQUENCE_TIMEOUT_PADDING_MS = 1200
const VOICE_REST_DURATION_INLINE_AUDIO = false
const VOICE_REST_DURATION_WARM_DOWNLOAD = true
const PLAN_PREVIEW_REQUEST_TIMEOUT_MS = 30000
const PLAN_TIME_BLOCKS_REQUEST_TIMEOUT_MS = 30000
const PLAN_TIME_BLOCKS_MAX_ATTEMPTS = 3
const PLAN_START_REQUEST_TIMEOUT_MS = 30000
const PLAN_START_MAX_ATTEMPTS = 3
const PLAN_START_RETRY_DELAY_MS = 300
const VIDEO_FEED_PREFETCH_COUNT = 0
const VIDEO_FEED_METADATA_AHEAD_COUNT = 5
const VIDEO_FEED_FIRST_FRAME_SIDE_COUNT = 5
const VIDEO_FEED_WATCH_MARK_DELAY_MS = 1200
const VIDEO_POSTER_PREFETCH_ENABLED = true
const VIDEO_POSTER_DISABLE_AFTER_FAIL_COUNT = 5
const VIDEO_POSTER_IMAGE_PRELOAD_ENABLED = true
const VIDEO_POSTER_PREFETCH_REQUEST_ENABLED = false
const VIDEO_POSTER_PREFETCH_CONCURRENCY = 2
const VIDEO_POSTER_PREFETCH_TIMEOUT_MS = 10000
const VIDEO_PROGRESS_UPDATE_INTERVAL_MS = 500
const VIDEO_PROGRESS_DRAG_UPDATE_INTERVAL_MS = 120
const VIDEO_PROGRESS_TAP_IGNORE_MS = 500
const VIDEO_SEEK_PLAY_DELAY_MS = 120
const VIDEO_SEEK_FALLBACK_PLAY_MS = 1200
const VIDEO_WAITING_LOG_INTERVAL_MS = 5000

const activeHost = USE_LOCAL_SERVER ? LOCAL_API_HOST : API_HOST
const activePort = USE_LOCAL_SERVER ? LOCAL_API_PORT : API_PORT

module.exports = {
  API_HOST,
  API_PORT,
  API_PROTOCOL,
  LOCAL_API_HOST,
  LOCAL_API_PORT,
  USE_LOCAL_SERVER,
  DEFAULT_REQUEST_TIMEOUT_MS,
  DEFAULT_REQUEST_MAX_ATTEMPTS,
  API_REQUEST_MAX_CONCURRENCY,
  API_BACKGROUND_REQUEST_MAX_CONCURRENCY,
  API_REQUEST_PRIORITY_HIGH,
  API_REQUEST_PRIORITY_NORMAL,
  API_REQUEST_PRIORITY_LOW,
  VOICE_TTS_PROVIDER_NONE,
  VOICE_TTS_PROVIDER_WECHAT_PLUGIN,
  VOICE_TTS_PROVIDER_SERVER,
  VOICE_TTS_PROVIDER,
  VOICE_SERVER_TTS_PATH,
  VOICE_TTS_REQUEST_TIMEOUT_MS,
  VOICE_TTS_MAX_ATTEMPTS,
  VOICE_TTS_RETRY_DELAY_MS,
  VOICE_PREPARE_REQUEST_TIMEOUT_MS,
  VOICE_PREPARE_MAX_ATTEMPTS,
  VOICE_PREPARE_RETRY_DELAY_MS,
  VOICE_INITIAL_REQUIRED_AUDIO_WAIT_MS,
  VOICE_REQUIRED_PREFETCH_TIMEOUT_MS,
  VOICE_INITIAL_REQUIRED_FETCH_CONCURRENCY,
  VOICE_PREFETCH_QUEUE_CONCURRENCY,
  VOICE_BACKGROUND_PREFETCH_CONCURRENCY,
  VOICE_BACKGROUND_FETCH_WAIT_MS,
  VOICE_BACKGROUND_FETCH_TIMEOUT_MS,
  VOICE_BACKGROUND_FETCH_MAX_ATTEMPTS,
  VOICE_FETCH_WAIT_MS,
  VOICE_FETCH_MAX_ATTEMPTS,
  VOICE_PREFETCH_DOWNLOAD_AUDIO,
  VOICE_AUDIO_DOWNLOAD_TIMEOUT_MS,
  VOICE_REST_DURATION_GRACE_MS,
  VOICE_REST_DURATION_REQUEST_TIMEOUT_MS,
  VOICE_REST_DURATION_MAX_ATTEMPTS,
  VOICE_REST_DURATION_RETRY_DELAY_MS,
  VOICE_REST_FIXED_FETCH_TIMEOUT_MS,
  VOICE_REST_FIXED_LOCAL_WAIT_MS,
  VOICE_REST_DURATION_LOCAL_WAIT_MS,
  VOICE_SEQUENCE_TIMEOUT_PADDING_MS,
  VOICE_REST_SEQUENCE_TIMEOUT_PADDING_MS,
  VOICE_REST_DURATION_INLINE_AUDIO,
  VOICE_REST_DURATION_WARM_DOWNLOAD,
  PLAN_PREVIEW_REQUEST_TIMEOUT_MS,
  PLAN_TIME_BLOCKS_REQUEST_TIMEOUT_MS,
  PLAN_TIME_BLOCKS_MAX_ATTEMPTS,
  PLAN_START_REQUEST_TIMEOUT_MS,
  PLAN_START_MAX_ATTEMPTS,
  PLAN_START_RETRY_DELAY_MS,
  VIDEO_FEED_PREFETCH_COUNT,
  VIDEO_FEED_METADATA_AHEAD_COUNT,
  VIDEO_FEED_FIRST_FRAME_SIDE_COUNT,
  VIDEO_FEED_WATCH_MARK_DELAY_MS,
  VIDEO_POSTER_PREFETCH_ENABLED,
  VIDEO_POSTER_DISABLE_AFTER_FAIL_COUNT,
  VIDEO_POSTER_IMAGE_PRELOAD_ENABLED,
  VIDEO_POSTER_PREFETCH_REQUEST_ENABLED,
  VIDEO_POSTER_PREFETCH_CONCURRENCY,
  VIDEO_POSTER_PREFETCH_TIMEOUT_MS,
  VIDEO_PROGRESS_UPDATE_INTERVAL_MS,
  VIDEO_PROGRESS_DRAG_UPDATE_INTERVAL_MS,
  VIDEO_PROGRESS_TAP_IGNORE_MS,
  VIDEO_SEEK_PLAY_DELAY_MS,
  VIDEO_SEEK_FALLBACK_PLAY_MS,
  VIDEO_WAITING_LOG_INTERVAL_MS,
  BASE_URL: `${API_PROTOCOL}://${activeHost}:${activePort}`
}