"$CLOUD_REBUILD" Cini 32 dll debug same
"$CLOUD_REBUILD" CHook 32 dll debug same
"$CLOUD_REBUILD" CStopWatch 32 dll debug same
"$CLOUD_REBUILD" ScreenScript 32 dll debug same
"$CLOUD_REBUILD" CKeyboard 32 dll debug only
"$CLOUD_REBUILD" CMouseConfig 32 dll debug only
"$CLOUD_REBUILD" CKeyboardConfig 32 dll debug only
"$CLOUD_REBUILD" QtControls 32 dll debug same
"$CLOUD_REBUILD" NetSender 32 dll debug same
"$CLOUD_REBUILD" AssignThreadManager 32 dll debug only
"$CLOUD_REBUILD" CommonTask 32 dll debug only