#pragma once

enum
{
	CAMERA_OK,
	CAMERA_HAS_NOT_OPEN,
	CAMERA_HAS_OPEN,
	CAMERA_OPEN_ING,
	CAMERA_CLOSE_ING,
	CAMERA_OPEN_ERROR,
	CAMERA_GRAB_ERROR
};

enum
{
	CAMERA_COMMAND_OPEN_CAMERA,
	CAMERA_COMMAND_CLOSE_CAMERA,
	CAMERA_COMMAND_FRAME_APPLY,
	CAMERA_COMMAND_FRAME_ABANDON,
	CAMERA_COMMAND_IS_OPEN,
	CAMERA_COMMAND_EXIT
};