"$CLOUD_REBUILD" CStopWatch 64 dll release same
"$CLOUD_REBUILD" DialogManager 64 dll release same
"$CLOUD_REBUILD" NetSender 64 dll release same
"$CLOUD_REBUILD" ScreenScript 64 dll release same
"$CLOUD_REBUILD" CKeyboard 64 dll release only
"$CLOUD_REBUILD" CMouseConfig 64 dll release same
"$CLOUD_REBUILD" CKeyboardConfig 64 dll release only
"$CLOUD_REBUILD" StockCharge 64 dll release same
"$CLOUD_REBUILD" SQLite 64 dll release same
"$CLOUD_REBUILD" SqlString 64 dll release same
"$CLOUD_REBUILD" HiRedis 64 dll release same
"$CLOUD_REBUILD" IntDateTime 64 dll release same
"$CLOUD_REBUILD" Cini 64 dll release same
"$CLOUD_REBUILD" Ctxt 64 dll release same
"$CLOUD_REBUILD" CStopWatch 64 dll release same
"$CLOUD_REBUILD" Timer 64 dll release same