"$CLOUD_REBUILD" CStopWatch 32 dll release same
"$CLOUD_REBUILD" DialogManager 32 dll release same
"$CLOUD_REBUILD" NetSender 32 dll release same
"$CLOUD_REBUILD" ScreenScript 32 dll release same
"$CLOUD_REBUILD" CKeyboard 32 dll release only
"$CLOUD_REBUILD" CMouseConfig 32 dll release same
"$CLOUD_REBUILD" CKeyboardConfig 32 dll release only
"$CLOUD_REBUILD" StockCharge 32 dll release same
"$CLOUD_REBUILD" SQLite 32 dll release same
"$CLOUD_REBUILD" SqlString 32 dll release same
"$CLOUD_REBUILD" HiRedis 32 dll release same